# Intro to Pytorch - Tensors

A deep learning research platform that provides maximum flexibility and speed

### Tensors

What is an array in numpy is called a tensor in pytorch. And tensors or numpy arrays can be changed from one another


In [35]:
import torch

# Make a Tensor
x = torch.Tensor(4,6) 
print x 
y = torch.rand(4,6)
print y
a = torch.ones(2,4)
print a


1.00000e-10 *
  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000
  0.0000  4.6566  0.0000  0.0000  0.0000  0.0000
[torch.FloatTensor of size 4x6]


 0.6616  0.9945  0.5736  0.7569  0.6309  0.3372
 0.2882  0.6051  0.4260  0.0714  0.8999  0.7592
 0.9089  0.8799  0.2501  0.4241  0.3436  0.2998
 0.7892  0.9875  0.0565  0.3858  0.6677  0.6135
[torch.FloatTensor of size 4x6]


 1  1  1  1
 1  1  1  1
[torch.FloatTensor of size 2x4]



In [36]:
# Get size
print 'size:', y.size()

size: torch.Size([4, 6])


In [37]:
# Change with Numpy (Same memory so changine one changes the other)
#   Tensor to np
b = a.numpy()
print b

#   np to Tensor
import numpy as np
f = np.ones(4)
print f
g = torch.from_numpy(f)
print f

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[ 1.  1.  1.  1.]
[ 1.  1.  1.  1.]


### Indexing into tensors
Indexing, a key aspect of numpy arrays is exactly the same for tensors

In [38]:
t = torch.ones(4,6)

print 'row 0', t[0,:]
print 'col 2', t[:, 2]

row 0 
 1
 1
 1
 1
 1
 1
[torch.FloatTensor of size 6]

col 2 
 1
 1
 1
 1
[torch.FloatTensor of size 4]



In [39]:
# Operations on Tensors (Docs: http://pytorch.org/docs/master/torch.html)

print torch.add(x, y) # One of the ways to add

print x.add_(y) # Another one of the ways to add


 0.6616  0.9945  0.5736  0.7569  0.6309  0.3372
 0.2882  0.6051  0.4260  0.0714  0.8999  0.7592
 0.9089  0.8799  0.2501  0.4241  0.3436  0.2998
 0.7892  0.9875  0.0565  0.3858  0.6677  0.6135
[torch.FloatTensor of size 4x6]


 0.6616  0.9945  0.5736  0.7569  0.6309  0.3372
 0.2882  0.6051  0.4260  0.0714  0.8999  0.7592
 0.9089  0.8799  0.2501  0.4241  0.3436  0.2998
 0.7892  0.9875  0.0565  0.3858  0.6677  0.6135
[torch.FloatTensor of size 4x6]



## Autograd

It is a package that allows us to differentiate  

Think of for example backpropgation in a neural network where we have $ Loss = out_{computed} - out_{desired}$ and where we want to change the weights so that we approach a loss of zero.  

Say we want to optimize $w_{i,j}$, the weight between two neurones 

We will do $\frac{\partial loss}{\partial w_{i,j}}$, by chaining through intermediate neurone outputs

Autograd can easily differentiate loss with respect to any of the variables involved in the net, doing the chaining automatically.

In the forward phase, autograd remembers all the operations it executed based on our definition of the net where we define a function that acts on inputs and a function that acts on this function in the first hidden layer etc.

In the backward phase, it will replay these operations and give us the derivatives.

In [84]:
import torch
from torch.autograd import Variable

input_tensor = torch.ones(1)

# Autograd has a `Variable` class which wraps around a `Tensor`
# (requires_grad=True to build the operations map)
inputs = Variable(input_tensor, requires_grad=True) 
print 'input Variable: ', inputs

# Can manipulate Variables
outputs = x**2 + 20
print 'output Variable: ', outputs

# Variable.data will return the `Tensor`
print 'Tensor in output Variable: ', outputs.data

# Variable.grad_fn holds history of all functions and variables 
# involved in reaching to this Variable
print 'Gradient fn to be used to compute gradient: ', outputs.grad_fn

# Backpropagation
# Call variable.backward to move back from output
# Backward takes in a loss etc (refer to NN section)

input Variable:  Variable containing:
 1
[torch.FloatTensor of size 1]

output Variable:  Variable containing:
 21  21  21
 21  21  21
[torch.FloatTensor of size 2x3]

Tensor in output Variable:  
 21  21  21
 21  21  21
[torch.FloatTensor of size 2x3]

Gradient fn to be used to compute gradient:  <torch.autograd.function.AddConstantBackward object at 0x10d4c9430>
